163204 Modifying solution template blades as per review comments
robe070/azure-quickstart-templates pull request #10
Opened 2020-08-25 08:00 UTC by ashutosh-kumar1

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Modified solution blades as per review comments
* Changes default git branch to support/scalable
* Added customImageId as output in mainTemplate to display the imageid in case of custom image verification.

2020-08-25 08:30 UTC, robe070 approved these changes

2020-08-25 23:43 UTC, robe070 requested changes
The json is fine and you can use it as it is, but I find the file naming confusing. I understand why you have named it as you have mssqlServer and mysqlServer, because they are creating the server and you are using the database type. But the resultant name is one character different and its not how we commonly refer to them. There may be an advantage in your naming if we were to have a simple loop on database type and could algorithmically work out the template name, but we have few databases and we will not be adding to them any time soon, if ever.

So please name the directory they are in as `DatabaseDeploymentTemplates`.
And the rest as:
myssqlParameters.json
mysqlTemplate.json
sqlServerParameters.json
sqlServerTemplate.json

2020-08-26 04:55 UTC, ashutosh-kumar1 commented
@robe070, Thanks for the review comments. The naming changes are done. Please merge the PR ASAP. We need these files to be added to the regression test in the pipeline.

2020-08-26 05:39 UTC, robe070 approved these changes

2020-08-26 05:39 UTC, merged