Adding Changes to mainTemplate #92
robe070/azure-quickstart-templates pull request #30
Opened 2021-07-26 10:59 UTC by Arshpreet1002

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

2021-07-27 02:13 UTC, robe070 requested changes

2021-07-27 02:13 UTC, robe070 commented on lansa-vmss-windows-autoscale-sql-database/mainTemplate.json
> +         "defaultValue": 2,
This needs to still be 1

2021-07-27 02:13 UTC, robe070 commented on lansa-vmss-windows-autoscale-sql-database/mainTemplate.json
> +         "minValue": 2,
Ditto

2021-07-27 02:13 UTC, robe070 commented on lansa-vmss-windows-autoscale-sql-database/mainTemplate.json
> +            "sourcePortRange": "*",
This SourcePort range must be the range of the NAT rules : natDBStartPort to natEndPort

2021-07-27 02:13 UTC, robe070 commented on lansa-vmss-windows-autoscale-sql-database/mainTemplate.json
> +            "capacity": 2
I said you needed to revert this change

2021-07-27 02:13 UTC, robe070 commented on lansa-vmss-windows-autoscale-sql-database/mainTemplate.json
> -                                    ],
This should not be removed.

2021-07-27 05:09 UTC, robe070 commented
In order to test that the AG is working to each of the VMSS, its required to manually remove the VMSS from the AG and then use the url to test the other VMSS is working.
So here:
![image](https://user-images.githubusercontent.com/4089160/127098767-98e5104e-c793-4d07-b7c5-2d80f80ebef8.png)

and then you can see that currently there is only 1 VMSS - because of the issue already identified in the template:
![image](https://user-images.githubusercontent.com/4089160/127098867-3386d01f-f4fb-49c5-9501-32537cd446e4.png)

And remove 1 of the VMSS to test it, then add it back in and remove the other

2021-07-27 05:26 UTC, robe070 commented
Please change dbVirtualMachineSize to have the same default as VirtualMachineSize. They are now equivalent VMs doing the same work. That is, Standard_B4ms

2021-07-27 05:29 UTC, robe070 commented
Add adding the VMSS failed with a 'try later' comment. Weird.

2021-07-27 07:59 UTC, robe070 commented
The pipeline is failing with a strange error. Have you deployed it yourself yet?

2021-07-27 09:06 UTC, Arshpreet1002 commented
I have checked it locally.It was running fine

2021-07-27 13:13 UTC, Arshpreet1002 commented
Ran Successfully.

2021-07-27 22:07 UTC, robe070 commented
so did you do the test in the AG to remove each of the VMSS in turn and test that the URL still worked?

2021-07-27 22:27 UTC, robe070 commented
> Please change dbVirtualMachineSize to have the same default as VirtualMachineSize. They are now equivalent VMs doing the same work. That is, Standard_B4ms

You still need to do this

2021-07-28 05:22 UTC, Arshpreet1002 commented
I have Tested By removing one of the VM's from AG and the URL is still Working.
And Chnaged the dbVitualMAchineSize to default .

2021-07-28 08:05 UTC, merged