Converted the classic pipeline to yaml Azure Templates CI
robe070/azure-quickstart-templates pull request #34
Opened 2024-09-26 13:03 UTC by Harinder-accolite

classic pipeline:-

repository: https://github.com/lansa/azure-quickstart-templates
branch: support/scalable
pipeline name - Template CI

converted classic to yaml pipeline

repository: Harinder-accolite/azure-quickstart-templates
branch: feature/harinder-classic2yaml
pipeline name: Azure Templates CI 
pipeline url: https://dev.azure.com/VisualLansa/Lansa%20Azure%20Scalable%20License%20Images/_build/results?buildId=2116&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a

2024-09-26 13:23 UTC, Harinder-accolite commented
Created the task to delete resource group as the Sql  Server (build-temsqlserver) was not getting deleted during the pipeline run.Is it okay that resource group is delete or we need to modify and delete only Sql Server.

2024-09-27 05:00 UTC, robe070 commented
> Created the task to delete resource group as the Sql Server (build-temsqlserver) was not getting deleted during the pipeline run.Is it okay that resource group is delete or we need to modify and delete only Sql Server.

Yes this is exactly what is required. Remove EVERYTHING that the creation of the Resource Group created. This is presuming that the resource group name is unique to this pipeline.

2024-09-27 14:21 UTC, Harinder-accolite commented
We have added the task to delete the resource group only when all the required task are successful.

2024-09-30 06:50 UTC, robe070 requested changes
As you may not delete it, you also need to delete it if it exists BEFORE you deploy the template. This means that you cannot include the Build Number in the resource group name.

Change the name the Resource Group to 
```
BakingDP-Templates-CI-Test
```

And add a Task to delete the RG BEFORE deploying the template - and if it does not exist that is FINE. Ignore the error.

2024-09-30 10:42 UTC, Harinder-accolite commented
Moved the Task for task for RG deletion and replaced the RG name to "BakingDP-Templates-CI-Test" also added the condition to continue if no RG is available if a resource is available the task will delete the RG and then Deploy the Template.

2024-09-30 22:30 UTC, robe070 commented on Azure Template CI.yaml
> -      resourceGroupName: BakingDP-TemplateTest-$(Build.BuildNumber)
I said to duplicate the task, not move it. You need to re-instate this task as it is.

2024-09-30 22:30 UTC, robe070 commented on Azure Template CI.yaml
> +      resourceGroupName: BakingDP-Templates-CI-Test
You need to make the RG Name a YAML variable.

2024-09-30 22:32 UTC, robe070 requested changes
Hopefully you understand my comments this time.

2024-10-01 06:40 UTC, Harinder-accolite commented on Azure Template CI.yaml
> +      resourceGroupName: BakingDP-Templates-CI-Test
Created the RG Name as YAML variable.

2024-10-02 05:03 UTC, robe070 commented on Azure Template CI.yaml
> -      resourceGroupName: BakingDP-TemplateTest-$(Build.BuildNumber)
You have still not done this!

2024-10-02 05:04 UTC, robe070 requested changes
The changes you made are fine, you've left one out, as I've separately commented.

2024-10-04 04:54 UTC, Harinder-accolite commented
Changes were made i.e task has been duplicated on the yaml and pushed to pipeline.

2024-10-04 07:23 UTC, Harinder-accolite commented
As per the discussion on the Call have deleted the task to continue on error at end of pipeline where as at the starting this task works fine.Ran the pipeline and artifact were created successfully .

2024-10-21 02:05 UTC, merged

2024-10-21 02:05 UTC, robe070 commented
Needed to change literal reference to resource group instead of $(ResourceGroup)

2024-10-25 12:33 UTC, nkhl-accolite commented
@robe070 - Do you mean you want to replace every "$(ResourceGroup)" with the actual value, which is "_BakingDP-Templates-CI-Test_"

2024-10-25 12:42 UTC, robe070 commented
What needs fixing? How will you know you've fixed it?

Leave it as it is. Run the pipeline. What's the symptom?